apiVersion : apps/v1
kind: Deployment
metadata:
  name: nginxapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
        - name: nginxapp
          image: poojareg.azurecr.io/nginxapp
          ports:
          - containerPort: 80
